# -*- coding: utf-8 -*-
"""emergency vehicle detection

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f-D2XaXXVSrcw4UdmPXUFKvhE79vGQx3
"""

# Commented out IPython magic to ensure Python compatibility.
# Download YOLOv7 repository and install requirements
!git clone https://github.com/WongKinYiu/yolov7
# %cd yolov7
!pip install -r requirements.txt

!wget https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7.pt

!unzip -q ../Sample_ambulance_data.zip -d ../

!python train.py --batch 2 --epochs 70 --data custom.yaml --weights yolov7.pt --cache

!python detect.py --weights  runs/train/exp/weights/best.pt --conf 0.25 --source ../videoplayback.mp4

python train.py --weights yolov7.pt --data custom.yaml --batch-size 4 --img 416 --cfg cfg/training/yolov7.yaml --name yolov7 --hyp data/hyp.scratch.p5.yaml

# REPLACE with your custom code snippet generated above

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="4M4LLjeNOcJKVDrEra4u")
project = rf.workspace("ss-fucku").project("amblance2")
dataset = project.version(2).download("yolov7")

pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio===0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

# Commented out IPython magic to ensure Python compatibility.
# download COCO starting checkpoint
# %cd /content/yolov7
!wget https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7_training.pt

# Commented out IPython magic to ensure Python compatibility.
# run this cell to begin training
# %cd /content/yolov7
!python train.py --batch 16 --epochs 6 --data {dataset.location}/data.yaml --weights 'yolov7_training.pt' --device 0